apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
spec:
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: mynginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 443
          name: http
        - containerPort: 80
          name: https
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    app: mynginx
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  type: LoadBalancer


