apiVersion: apps/v1 # до версии 1.9.0 нужно использовать apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: ngin
  replicas: 1 # запускает 2 пода, созданных по шаблону
  template:
    metadata:
      labels:
        app: ngin
    spec:
      containers:
      - name: ngin
        imagePullPolicy: Never
        image: ngin
        ports:
        - containerPort: 80
        - containerPort: 443