apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps-con
        - containerPort: 20
          name: ftps-dt
        - containerPort: 21000
          name: ftps-pass

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    name: connect
  - port: 20
    name: data
  - port: 21000
    name: pass
  loadBalancerIP: 192.168.99.112
  type: LoadBalancer

  